[package]
name = "pluvius"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.6.0"
candle-onnx = "0.6.0"
chrono = "0.4.38"
csv = "1.3.0"
polars = {version = "0.42.0", features = ["csv", "lazy"]}
serde = "1.0.209"
