version: '3'

services:
  feature_store:
    image: mongo:latest
    container_name: pluvius_feature_store
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: pluvius
      MONGO_INITDB_ROOT_PASSWORD: local_password
    volumes:
      - feature_store:/data/db


volumes:
  feature_store:
    driver: local
