version: '3'

services:
  feature_extractor_worker:
    image: pluvius/feature-extractor:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: feature_store
      DB_NAME: admin
      DB_USER: pluvius
      DB_PASSWORD: local_password
    networks:
      - pluvius
      
  feature_store:
    image: mongo:latest
    container_name: pluvius_feature_store
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: pluvius
      MONGO_INITDB_ROOT_PASSWORD: local_password
      MONGO_INITDB_DATABASE: feature_store
    volumes:
      - feature_store:/data/db
    networks:
      - pluvius


volumes:
  feature_store:
    driver: local
networks:
  pluvius:
    driver: bridge
